export const productsList = {
  uk: [
    {
      id: "assorted",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Асорті огірків та томатів",
      volume: "720",
    },
    {
      id: "assorted",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Асорті огірків та томатів",
      volume: "900",
    },
    {
      id: "assorted",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Асорті огірків та томатів",
      volume: "1500",
    },
    {
      id: "assorted",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Асорті огірків та томатів",
      volume: "1850",
    },
    {
      id: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "480",
    },
    {
      id: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "540",
    },
    {
      id: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "550",
    },
    {
      id: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "720",
    },
    {
      id: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "900",
    },
    {
      id: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "1500",
    },
    {
      id: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "480",
    },
    {
      id: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "540",
    },
    {
      id: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "720",
    },
    {
      id: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "900",
    },
    {
      id: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "1000",
    },
    {
      id: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "1500",
    },
    {
      id: "tomatoes",
      trademark: { id: "ukrpole", title: "Укрполе" },
      title: "Томати",
      volume: "540",
    },
    {
      id: "tomatoes",
      trademark: { id: "ukrpole", title: "Укрполе" },
      title: "Томати",
      volume: "720",
    },
    {
      id: "peppers",
      trademark: { id: "ukrpole", title: "Укрполе" },
      title: "Перець",
      volume: "720",
    },
    {
      id: "peppers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Перець",
      volume: "720",
    },
  ],
  en: [],
};
