export const productsList = {
  uk: [
    {
      category: "assorted",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Асорті огірків та томатів",
      volume: "720",
      energyValue: {
        kJ: "184",
        kcal: "44",
        protein: "0,39",
        fat: "0,005",
        carbohydrates: "7,9",
        sugars: "5,5",
        salt: "1,7",
      },
      ingredients: [
        "tomatoes",
        "cucumbers",
        "water",
        "sugar",
        "salt",
        "vinegar",
        "fennel",
        "garlic",
        "mustard",
        "peppercorns",
        "bayLeaf",
      ],
      description:
        "Мариновані огірки й помідори в ароматному розсолі з кропом та спеціями. Хрусткі, соковиті, без штучних добавок — ідеальні до будь-якої страви!",
    },
    {
      category: "assorted",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Асорті огірків та томатів",
      volume: "900",
      energyValue: {
        kJ: "184",
        kcal: "44",
        protein: "0,39",
        fat: "0,005",
        carbohydrates: "7,9",
        sugars: "5,5",
        salt: "1,7",
      },
      ingredients: [
        "tomatoes",
        "cucumbers",
        "water",
        "sugar",
        "salt",
        "vinegar",
        "fennel",
        "garlic",
        "mustard",
        "peppercorns",
        "bayLeaf",
      ],
      description:
        "Мариновані огірки й помідори в ароматному розсолі з кропом та спеціями. Хрусткі, соковиті, без штучних добавок — ідеальні до будь-якої страви!",
    },
    {
      category: "assorted",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Асорті огірків та томатів",
      volume: "1500",
      energyValue: {
        kJ: "184",
        kcal: "44",
        protein: "0,39",
        fat: "0,005",
        carbohydrates: "7,9",
        sugars: "5,5",
        salt: "1,7",
      },
      ingredients: [
        "tomatoes",
        "cucumbers",
        "water",
        "sugar",
        "salt",
        "vinegar",
        "fennel",
        "garlic",
        "mustard",
        "peppercorns",
        "bayLeaf",
      ],
      description:
        "Мариновані огірки й помідори в ароматному розсолі з кропом та спеціями. Хрусткі, соковиті, без штучних добавок — ідеальні до будь-якої страви!",
    },
    {
      category: "assorted",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Асорті огірків та томатів",
      volume: "1850",
      energyValue: {
        kJ: "184",
        kcal: "44",
        protein: "0,39",
        fat: "0,005",
        carbohydrates: "7,9",
        sugars: "5,5",
        salt: "1,7",
      },
      ingredients: [
        "tomatoes",
        "cucumbers",
        "water",
        "sugar",
        "salt",
        "vinegar",
        "fennel",
        "garlic",
        "mustard",
        "peppercorns",
        "bayLeaf",
      ],
      description:
        "Мариновані огірки й помідори в ароматному розсолі з кропом та спеціями. Хрусткі, соковиті, без штучних добавок — ідеальні до будь-якої страви!",
    },
    {
      category: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "480",
      energyValue: {
        kJ: "121",
        kcal: "29",
        protein: "0,48",
        fat: "0,005",
        carbohydrates: "4,32",
        sugars: "2,6",
        salt: "1,7",
      },
      ingredients: [
        "tomatoes",
        "cucumbers",
        "water",
        "sugar",
        "salt",
        "vinegar",
        "fennel",
        "garlic",
        "mustard",
        "peppercorns",
        "bayLeaf",
      ],
      description:
        "Хрусткі мариновані огірки з ніжним ароматом кропу, часнику та спецій. Натуральний смак без зайвих добавок, ідеальні як закуска чи гарнір!",
    },
    {
      category: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "540",
      description:
        "Хрусткі мариновані огірки з ніжним ароматом кропу, часнику та спецій. Натуральний смак без зайвих добавок, ідеальні як закуска чи гарнір!",
    },
    {
      category: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "580",
      description:
        "Хрусткі мариновані огірки з ніжним ароматом кропу, часнику та спецій. Натуральний смак без зайвих добавок, ідеальні як закуска чи гарнір!",
    },
    {
      category: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "720",
      description:
        "Хрусткі мариновані огірки з ніжним ароматом кропу, часнику та спецій. Натуральний смак без зайвих добавок, ідеальні як закуска чи гарнір!",
    },
    {
      category: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "900",
      description:
        "Хрусткі мариновані огірки з ніжним ароматом кропу, часнику та спецій. Натуральний смак без зайвих добавок, ідеальні як закуска чи гарнір!",
    },
    {
      category: "cucumbers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Огірки",
      volume: "1500",
      weight: "720",
      energyValue: {
        kJ: "268",
        kcal: "64",
        protein: "0,72",
        fat: "3",
        carbohydrates: "8,5",
        sugars: "6,7",
        salt: "1,7",
      },
      ingredients: [
        "Томати",
        "Вода питна",
        "Цукор",
        "Сіль кухонна",
        "Кислота оцтова",
        "Часник сушений",
        "Перець чорний",
      ],
      description:
        "Хрусткі мариновані огірки з ніжним ароматом кропу, часнику та спецій. Натуральний смак без зайвих добавок, ідеальні як закуска чи гарнір!",
    },
    {
      category: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати Челісімо",
      volume: "480",
      description:
        "Смачні томати Челісімо в легкому маринаді. Зберігають соковитість і яскравий аромат, створені для насолоди в кожному шматочку!",
    },
    {
      category: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "540",
      description:
        "Соковиті мариновані томати з ніжним ароматом кропу та часнику. Збережений натуральний смак, ідеально доповнять будь-яку страву чи закуску!",
    },
    {
      category: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "720",
      description:
        "Соковиті мариновані томати з ніжним ароматом кропу та часнику. Збережений натуральний смак, ідеально доповнять будь-яку страву чи закуску!",
    },
    {
      category: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "900",
      description:
        "Соковиті мариновані томати з ніжним ароматом кропу та часнику. Збережений натуральний смак, ідеально доповнять будь-яку страву чи закуску!",
    },
    {
      category: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "1000",
      description:
        "Соковиті мариновані томати з ніжним ароматом кропу та часнику. Збережений натуральний смак, ідеально доповнять будь-яку страву чи закуску!",
    },
    {
      category: "tomatoes",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Томати",
      volume: "1500",
      description:
        "Соковиті мариновані томати з ніжним ароматом кропу та часнику. Збережений натуральний смак, ідеально доповнять будь-яку страву чи закуску!",
    },
    {
      category: "tomatoes",
      trademark: { id: "ukrpole", title: "Укрполе" },
      title: "Томати",
      volume: "540",
      description:
        "Соковиті помідори в ароматному маринаді зі спеціями. Збалансований смак і натуральність роблять їх чудовим вибором для вашого столу!",
    },
    {
      category: "tomatoes",
      trademark: { id: "ukrpole", title: "Укрполе" },
      title: "Томати",
      volume: "720",
      description:
        "Соковиті помідори в ароматному маринаді зі спеціями. Збалансований смак і натуральність роблять їх чудовим вибором для вашого столу!",
    },
    {
      category: "peppers",
      trademark: { id: "ukrpole", title: "Укрполе" },
      title: "Перець",
      volume: "720",
      description:
        "Солодкий маринований перець із ніжним ароматом спецій. Зберігає натуральний смак і текстуру, ідеально підходить для закусок та салатів.",
    },
    {
      category: "peppers",
      trademark: { id: "bataljon", title: "Батальйон Смаку" },
      title: "Перець",
      volume: "720",
      energyValue: {
        kJ: "268",
        kcal: "64",
        protein: "0,72",
        fat: "3",
        carbohydrates: "8,5",
        sugars: "6,7",
        salt: "1,7",
      },
      ingredients: [
        "tomatoes",
        "water",
        "sugar",
        "salt",
        "vinegar",
        "garlic",
        "peppercorns",
      ],
      description:
        "Яскравий солодкий перець у пряному маринаді. Хрусткий і ароматний, він стане чудовим доповненням до страв або окремою закускою!",
    },
  ],
  en: [],
};
