export const productsList = {
  uk: [
    {
      id: "assorted",
      trademark: "Батальйон смаку",
      category: "Асорті огірків та томатів",
      volume: "720",
    },
    {
      id: "assorted",
      trademark: "Батальйон смаку",
      category: "Асорті огірків та томатів",
      volume: "900",
    },
    {
      id: "assorted",
      trademark: "Батальйон смаку",
      category: "Асорті огірків та томатів",
      volume: "1500",
    },
    {
      id: "assorted",
      trademark: "Батальйон смаку",
      category: "Асорті огірків та томатів",
      volume: "1850",
    },
    {
      id: "cucumbers",
      trademark: "Батальйон смаку",
      category: "Огірки",
      volume: "480",
    },
    {
      id: "cucumbers",
      trademark: "Батальйон смаку",
      category: "Огірки",
      volume: "540",
    },
    {
      id: "cucumbers",
      trademark: "Батальйон смаку",
      category: "Огірки",
      volume: "550",
    },
    {
      id: "cucumbers",
      trademark: "Батальйон смаку",
      category: "Огірки",
      volume: "720",
    },
    {
      id: "cucumbers",
      trademark: "Батальйон смаку",
      category: "Огірки",
      volume: "900",
    },
    {
      id: "cucumbers",
      trademark: "Батальйон смаку",
      category: "Огірки",
      volume: "1500",
    },
    {
      id: "tomatoes",
      trademark: "Батальйон смаку",
      category: "Томати",
      volume: "480",
    },
    {
      id: "tomatoes",
      trademark: "Батальйон смаку",
      category: "Томати",
      volume: "540",
    },
    {
      id: "tomatoes",
      trademark: "Батальйон смаку",
      category: "Томати",
      volume: "720",
    },
    {
      id: "tomatoes",
      trademark: "Батальйон смаку",
      category: "Томати",
      volume: "900",
    },
    {
      id: "tomatoes",
      trademark: "Батальйон смаку",
      category: "Томати",
      volume: "1000",
    },
    {
      id: "tomatoes",
      trademark: "Батальйон смаку",
      category: "Томати",
      volume: "1500",
    },
    {
      id: "tomatoes",
      trademark: "Укрполе",
      category: "Томати",
      volume: "540",
    },
    {
      id: "tomatoes",
      trademark: "Укрполе",
      category: "Томати",
      volume: "720",
    },
    {
      id: "peppers",
      trademark: "Укрполе",
      category: "Перець",
      volume: "720",
    },
    {
      id: "peppers",
      trademark: "Батальйон смаку",
      category: "Перець",
      volume: "720",
    },
  ],
  en: [],
};
