import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import "./globals.css";
import { Locale } from "@/types/locale";
import { Montserrat, Alegreya_Sans_SC } from "next/font/google";

const montserrat = Montserrat({
  weight: ["400", "500"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-montserrat",
});

const alegreya = Alegreya_Sans_SC({
  weight: ["500"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-alegreya",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html lang={locale} className="scroll-smooth">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body
        className={`${montserrat.variable} ${alegreya.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
